### PR TITLE
Added Django, ML, blockchain and Image Processing tutorials

### PR DESCRIPTION
**Pull request by sayands**

### CODE REVIEW

**Comment by sayands** [comment]
@tuvtran please take a look at these tutorials.

**Comment by tuvtran** [comment]
Sorry I've been busy with work recently. I will review those changes soon (later today or this week). Thanks a lot for finding awesome resources!

**Comment by sayands** [comment]
@tuvtran Did you check these out yet ?

**Comment by sayands** [comment]
Did you check the tutorials out yet @tuvtran ?

**Comment by tuvtran** [comment]
Yes I did. Could you re-open this issue so that I can resolve some merge conflicts?

**Pull request closed without merging**
