### PR TITLE
Adding Flutter Tutorials

### PR DESCRIPTION
**Pull request by RivaanRanawat**
Added Flutter Tutorials in Dart Subsection

## Description
Added Flutter Full Stack Projects and UI Tutorials to the list. Created New List with Dart as the main category and Flutter as sub category.

## Motivation and Context
Fixes issue #282 - https://github.com/practical-tutorials/project-based-learning/issues/282

## How Has This Been Tested?
All the tutorials in this project are up-to-date.

## Types of changes
- [x] Content Update (change which fixes an issue or updates an already existing submission)
- [ ] New Article (change which adds functionality)
- [x] Documentation change

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have made checks to ensure URLs and other resources are valid

### CODE REVIEW

**Comment by enkeyz** [comment]
I can't accept the last one, because it shows only the creation of the user interface. Removed that, and I'll merge.

**Comment by RivaanRanawat** [comment]
Done, thank you :)

**Review by pawan1612 — COMMENTED** [review]
NA

**Review by Lishkk — APPROVED** [review]

**Comment by Lishkk** [comment]
> I can't accept the last one, because it shows only the creation of the user interface. Removed that, and I'll merge.

**Pull request merged**
