### PR TITLE
Delete a WRONG and EXISTED item.

### PR DESCRIPTION
**Pull request by fake-rookie**
**Delete a WRONG and EXISTED item.**

## Description

**That is not an OCaml project.  It's a C++ project.**

## Motivation and Context

**Not nedd fix. Just delete it. And alread existed in C/C++ option. 
Named "Implementing a Language with LLVM" under C/C++** 

## How Has This Been Tested?

**Just click that link to see.**

## Types of changes

- [x] Content Update (change which fixes an issue or updates an already existing submission)
- [ ] New Article (change which adds functionality)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have made checks to ensure URLs and other resources are valid

### CODE REVIEW

**Comment by fake-rookie** [comment]
The 2nd one:



**This is another WRONG item.**

## Description


**That is not an OCaml project.  It's a C++ project.**

## Motivation and Context



**That is only a RECORD or JORUNAL.
Even not to explain what is a KEY-VALUE Database.** 

## How Has This Been Tested?




**Just click that link to see the DETAIL.**

## Types of changes

- [x] Content Update (change which fixes an issue or updates an already existing submission)
- [ ] New Article (change which adds functionality)
- [ ] Documentation change

## Checklist:


- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have made checks to ensure URLs and other resources are valid

**Comment by fake-rookie** [comment]
@enkeyz Mate. I'm not wrong. just delete once. 

2022-09-29-162148_1735x735_scrot




And the 2nd pr also right. That is a **FUCKING** "RECORD" or "JOURNEY" things.
**NOT A PROJECT**.
Like i said. 
Even **not** a explain.

**Comment by fake-rookie** [comment]
2022-09-29-163341_1670x1042_scrot



Where is the  **deleted both** ?

I can not see.

**Comment by nehaaaa6** [comment]
Open your C++ project in your IDE or text editor.
Locate the item "Implementing a Language with LLVM" under the C/C++ option.
Delete the item by either right-clicking on it and selecting "Delete" or by pressing the delete key on your keyboard.
Save the changes to your project file

**Pull request closed without merging**
